# Generated by Django 5.0.3 on 2024-04-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_account_picture.png', upload_to='account_pictures', verbose_name='Image'),
        ),
    ]
