# Generated by Django 5.2 on 2025-04-28 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikidataEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=20, unique=True, verbose_name='Идентификатор Q')),
                ('label_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Метка на русском')),
                ('label_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Метка на английском')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание на русском')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание на английском')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='Свойства и значения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сущность Wikidata',
                'verbose_name_plural': 'Сущности Wikidata',
                'ordering': ['qid'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='enhancer.folder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='docs/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('doc', 'Word'), ('docx', 'Word (new)'), ('rtf', 'Rich Text')], max_length=10, verbose_name='Тип файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое документа')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enhancer.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEntityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_category', models.CharField(blank=True, choices=[('creator', 'Creator'), ('organizations', 'Organizations'), ('title', 'Title'), ('keywords', 'Keywords'), ('subject', 'Subject'), ('document_language', 'Document Language'), ('contributor', 'Contributor')], max_length=50, null=True, verbose_name='Категория поля')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя сущности')),
                ('confidence', models.FloatField(default=1.0, verbose_name='Уверенность связи')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Контекст упоминания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_relations', to='enhancer.document', verbose_name='Документ')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_relations', to='enhancer.wikidataentity', verbose_name='Сущность Wikidata')),
            ],
            options={
                'verbose_name': 'Связь документа с сущностью',
                'verbose_name_plural': 'Связи документов с сущностями',
                'ordering': ['-confidence'],
            },
        ),
    ]
