# Generated by Django 5.2 on 2025-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('success', 'Успешно'), ('failed', 'Не удалось')], default='pending', max_length=20, verbose_name='Статус обработки'),
        ),
        migrations.AlterUniqueTogether(
            name='documententityrelation',
            unique_together={('document', 'entity', 'field_category', 'name')},
        ),
    ]
