# Generated by Django 5.2 on 2025-04-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0002_document_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_errors',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибки обработки'),
        ),
        migrations.AddField(
            model_name='document',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID задачи Celery'),
        ),
    ]
