# Generated by Django 5.2 on 2025-04-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0003_document_processing_errors_document_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='meta_wikidata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Связи метаданных с Wikidata'),
        ),
    ]
