# Generated by Django 5.2 on 2025-05-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0004_document_meta_wikidata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documententityrelation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documententityrelation',
            name='field_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ поля метаданных'),
        ),
        migrations.AddField(
            model_name='documententityrelation',
            name='field_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение поля метаданных'),
        ),
        migrations.AlterUniqueTogether(
            name='documententityrelation',
            unique_together={('document', 'entity', 'field_category', 'field_key', 'field_value')},
        ),
    ]
